name: XMLA to BIM & Upload to Power BI

on:
  push:
    paths:
      - "aa.xmla"  # Trigger only when aa.xmla is modified
  workflow_dispatch:  # Allow manual runs

jobs:
  convert_and_upload:
    runs-on: windows-latest  # Ensure Windows for Tabular Editor
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print XMLA File Location
        shell: pwsh
        run: |
          $xmlaPath = (Resolve-Path "aa.xmla").Path
          Write-Host "XMLA file is stored at: $xmlaPath"

      - name: Download & Extract Tabular Editor
        run: |
          $url = "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip"
          Invoke-WebRequest -Uri $url -OutFile "TabularEditor.zip"
          Expand-Archive -Path "TabularEditor.zip" -DestinationPath "TabularEditor"
          Remove-Item "TabularEditor.zip"

      - name: Verify Tabular Editor Exists
        run: |
          Write-Host "Verifying Tabular Editor..."
          Test-Path "TabularEditor\TabularEditor.exe"

      - name: Convert XMLA to BIM
        shell: pwsh
        run: |
          Write-Host "Creating output directory for BIM..."
          New-Item -ItemType Directory -Path "bim_output" -Force

          Write-Host "Converting XMLA to BIM..."
          $xmlaPath = (Resolve-Path "aa.xmla").Path
          $bimPath = (Resolve-Path "bim_output").Path + "\Model.bim"

          .\TabularEditor\TabularEditor.exe "$xmlaPath" -B "$bimPath"
          Write-Host "Conversion complete. BIM file stored at: $bimPath"

      - name: Display BIM File Location
        shell: pwsh
        run: |
          $bimPath = (Resolve-Path "bim_output\Model.bim").Path
          Write-Host "BIM file created at: $bimPath"

      - name: Upload BIM to Power BI Workspace
        shell: pwsh
        run: |
          Write-Host "Uploading BIM to Power BI Workspace..."
          $bimPath = (Resolve-Path "bim_output\Model.bim").Path
          .\TabularEditor\TabularEditor.exe "$bimPath" -D "powerbi://api.powerbi.com/v1.0/myorg/Tungsten%20Automation" -O
          Write-Host "Upload complete."
