name: XMLA to BIM & Upload to Power BI

on:
  push:
    paths:
      - "aa.xmla"  # Trigger only when aa.xmla is modified
  workflow_dispatch:  # Allow manual runs

jobs:
  convert_and_upload:
    runs-on: windows-latest  # Ensure Windows for Tabular Editor
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download & Extract Tabular Editor
        run: |
          $url = "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip"
          Invoke-WebRequest -Uri $url -OutFile "TabularEditor.zip"
          Expand-Archive -Path "TabularEditor.zip" -DestinationPath "TabularEditor"
          Remove-Item "TabularEditor.zip"

      - name: Verify Tabular Editor Exists
        run: |
          Write-Host "Verifying Tabular Editor..."
          Test-Path "TabularEditor\TabularEditor.exe"

      - name: Convert XMLA to BIM
        shell: pwsh
        run: |
          Write-Host "Converting XMLA to BIM..."
          .\TabularEditor\TabularEditor.exe "aa.xmla" -B "Model.bim"
          Write-Host "Conversion complete."

      - name: Upload BIM to Power BI Workspace
        shell: pwsh
        run: |
          Write-Host "Uploading BIM to Power BI Workspace..."
          .\TabularEditor\TabularEditor.exe Model.bim -D "powerbi://api.powerbi.com/v1.0/myorg/Tungsten%20Automation" -O
          Write-Host "Upload complete."
