name: Deploy XMLA to Power BI

on:
  push:
    paths:
      - "aa.xmla"  # Trigger only if aa.xmla changes
  workflow_dispatch:

jobs:
  deploy_to_pbi:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify XMLA File Exists
        shell: pwsh
        run: |
          if (Test-Path "aa.xmla") {
            Write-Host "✅ aa.xmla found"
          } else {
            Write-Host "❌ aa.xmla NOT found. Stopping workflow."
            exit 1
          }

      - name: Download & Install Tabular Editor
        run: |
          Invoke-WebRequest -Uri "https://github.com/TabularEditor/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip" -OutFile "TabularEditor.zip"
          Expand-Archive -Path "TabularEditor.zip" -DestinationPath "TabularEditor"
          Remove-Item "TabularEditor.zip"
          Get-ChildItem -Path TabularEditor  # Debug: Check contents

      - name: Convert XMLA to BIM
        run: |
          $editorPath = Get-ChildItem -Path TabularEditor -Filter "TabularEditor.exe" -Recurse | Select-Object -ExpandProperty FullName
          if ($editorPath) {
            & $editorPath -S "aa.xmla" -B "Model.bim"
          } else {
            Write-Host "❌ TabularEditor.exe NOT found"
            exit 1
          }
        shell: pwsh

      - name: Verify BIM File Exists
        shell: pwsh
        run: |
          if (Test-Path "Model.bim") {
            Write-Host "✅ Model.bim created successfully"
          } else {
            Write-Host "❌ Model.bim NOT found. Stopping workflow."
            exit 1
          }

      - name: Upload BIM to Power BI Workspace
        run: |
          $editorPath = Get-ChildItem -Path TabularEditor -Filter "TabularEditor.exe" -Recurse | Select-Object -ExpandProperty FullName
          if ($editorPath) {
            & $editorPath "Model.bim" -D "powerbi://api.powerbi.com/v1.0/myorg/Tungsten%20Automation" -O
          } else {
            Write-Host "❌ TabularEditor.exe NOT found for upload"
            exit 1
          }
        shell: pwsh
