name: Convert XMLA to BIM and Upload to Power BI

on:
  push:
    paths:
      - "aa.xmla"  # Trigger only when aa.xmla file changes
    branches:
      - main

jobs:
  convert-and-upload:
    runs-on: windows-latest  # Using a Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Extract Tabular Editor
        run: |
          Invoke-WebRequest -Uri "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip" -OutFile "TabularEditor.zip"
          Expand-Archive -Path "TabularEditor.zip" -DestinationPath "TabularEditor"
          Remove-Item "TabularEditor.zip"
      
      - name: Convert XMLA to BIM
        run: |
          ./TabularEditor/TabularEditor.exe aa.xmla -B Model.bim

      - name: Upload BIM to Power BI Workspace
        run: |
          ./TabularEditor/TabularEditor.exe Model.bim -D "powerbi://api.powerbi.com/v1.0/myorg/Tungsten%20Automation" -O
