name: XMLA to BIM & Upload to Power BI

on:
  push:
    paths:
      - "aa.xmla"  # Trigger only when aa.xmla is modified
  workflow_dispatch:  # Allow manual runs

jobs:
  convert_and_upload:
    runs-on: windows-latest  # Ensure Windows for Tabular Editor
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download & Extract Tabular Editor
        run: |
          $url = "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip"
          Invoke-WebRequest -Uri $url -OutFile "TabularEditor.zip"
          Expand-Archive -Path "TabularEditor.zip" -DestinationPath "TabularEditor"
          Remove-Item "TabularEditor.zip"

      - name: Verify Tabular Editor Exists
        run: |
          if (!(Test-Path "TabularEditor\TabularEditor.exe")) {
            Write-Host "❌ TabularEditor.exe NOT found!"
            exit 1
          } else {
            Write-Host "✅ TabularEditor.exe found!"
          }

      - name: Convert XMLA to BIM
        shell: pwsh
        run: |
          # Check if aa.xmla file exists
          if (!(Test-Path "aa.xmla")) {
            Write-Host "❌ aa.xmla NOT found!"
            exit 1
          } else {
            Write-Host "✅ aa.xmla found, proceeding with conversion"
          }

          # Run Tabular Editor conversion
          & TabularEditor\TabularEditor.exe "aa.xmla" -B "Model.bim"

          # Verify Model.bim creation
          if (!(Test-Path "Model.bim")) {
            Write-Host "❌ Model.bim NOT created!"
            exit 1
          } else {
            Write-Host "✅ Model.bim created successfully"
          }

      - name: Upload BIM to Power BI Workspace
        shell: pwsh
        run: |
          & TabularEditor\TabularEditor.exe Model.bim -D "powerbi://api.powerbi.com/v1.0/myorg/Tungsten%20Automation" -O
